
#@server = https://luisangelri-glowing-journey-ggwww4ww647hwx6p-8080.preview.app.github.dev
@server = https://sem8-m09t.onrender.com
@apiserver ={{server}}/api/curso
###

GET {{server}}/
###

GET {{server}}/codigo
###

GET {{server}}/nombre-completo
###

GET {{apiserver}}/listar
###

POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Lenguajes+de+programacion&creditos=4
###

DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=5
###
